blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls'))
]

blog/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=255)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Article(models.Model):
    name = models.CharField(max_length=255)
    content = models.CharField(max_length=255)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('news:detail', kwargs={'pk': self.pk})

blog/views.py
from django.urls import reverse_lazy
from django.views import generic
from .models import Category, Article

class IndexView(generic.ListView):
    model = Article

class DetailView(generic.DetailView):
    model = Article

class CreateView(generic.edit.CreateView):
    model = Article
    fields = '__all__'

class UpdateView(generic.edit.UpdateView):
    model = Article
    fields = '__all__'

class DeleteView(generic.edit.DeleteView):
    model = Article
    success_url = reverse_lazy('blog:index')

blog/templates/blog/article_confirm_delete.html
{% extends './base.html' %}
{% block content %}

<h1>記事の削除</h1>
<p>'{{ object.name }}'を削除しますか?</p>
<form action='' method='post'>{% csrf_token %}
    <input type="submit" value="削除" class="btn btn-danger" />

</form> -->

<div>
    <p><a href='JavaScript:history.back()'>&lt; 戻る</a></p>
</div>

{% endblock %}

blog/templates/blog/article_detail.html
{% extends './base.html' %}
{% block content %}
    <h1>{{ article.name }}</h1>
    <div>
        <p>{{ article.category.name }}</p>
        <p>{{ article.content}}</p>
    </div>
    <div>
        <a href='{% url "blog:index" %}'>一覧</a> |
        <a href='{% url "blog:update" article.pk %}'>編集</a> |
        <a href='{% url "blog:delete" article.pk %}'>削除</a>
    </div>
{% endblock %}

blog/templates/blog/article_forms.html
{% extends './base.html' %}
{% block content %}

<h1>記事の{{ object|yesno:'更新,作成'}}</h1>

<form action='' method='post'>{% csrf_token %}
    {{ form.as_p }}
    <button type='submit' class='submit'>{{ object|yesno:'更新,作成'}}</button>
</form>
<div>
    <a href='JavaScript:history.back()'>&lt; 戻る</a>
</div>

{% endblock %}

blog/templates/blog/article_list.html
{% extends './base.html' %}
{% block content %}

<h1>記事一覧</h1>
<table class='table table-striped table-hover'>
    <tr>
        <th>カテゴリ</th><th>記事名</th><th>内容</th>
    </tr>
    {% for article in object_list %}
    <tr>
        <td>{{ article.category.name }}</td>
        <td><a href='{% url "blog:detail" article.pk %}'>{{ article.name }}</a></td>
        <td>{{ article.content }}</td>
    </tr>
    {% endfor %}
</table>
    <div>
        <a href='{% url "blog:create" %}'>新しい記事</a>
    </div>

{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
        <style>body {padding-top: 80px;}</style>
        <title>News</title>
    </head>
    <body>
        <nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "blog:index" %}'>🐮🐮BLOG</a>
        </nav>
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>